package codes

import tm "github.com/jonvaldes/termo"

var (
	ESC     = tm.ScanCode{27, 0, 0, 0, 0, 0}
	UP      = tm.ScanCode{27, 91, 65, 0, 0, 0}
	DOWN    = tm.ScanCode{27, 91, 66, 0, 0, 0}
	LEFT    = tm.ScanCode{27, 91, 68, 0, 0, 0}
	RIGHT   = tm.ScanCode{27, 91, 67, 0, 0, 0}
	BACKSP  = tm.ScanCode{127, 0, 0, 0, 0, 0}
	TAB     = tm.ScanCode{9, 0, 0, 0, 0, 0}
	ENTER   = tm.ScanCode{13, 0, 0, 0, 0, 0}
	HOME    = tm.ScanCode{27, 79, 72, 0, 0, 0}
	END     = tm.ScanCode{27, 79, 70, 0, 0, 0}
	DEL	= tm.ScanCode{27, 91, 51, 126, 0, 0}

	//Autogenerated
	CA      = tm.ScanCode{65, 0, 0, 0, 0, 0}
	CB      = tm.ScanCode{66, 0, 0, 0, 0, 0}
	CC      = tm.ScanCode{67, 0, 0, 0, 0, 0}
	CD      = tm.ScanCode{68, 0, 0, 0, 0, 0}
	CE      = tm.ScanCode{69, 0, 0, 0, 0, 0}
	CF      = tm.ScanCode{70, 0, 0, 0, 0, 0}
	CG      = tm.ScanCode{71, 0, 0, 0, 0, 0}
	CH      = tm.ScanCode{72, 0, 0, 0, 0, 0}
	CI      = tm.ScanCode{73, 0, 0, 0, 0, 0}
	CJ      = tm.ScanCode{74, 0, 0, 0, 0, 0}
	CK      = tm.ScanCode{75, 0, 0, 0, 0, 0}
	CL      = tm.ScanCode{76, 0, 0, 0, 0, 0}
	CM      = tm.ScanCode{77, 0, 0, 0, 0, 0}
	CN      = tm.ScanCode{78, 0, 0, 0, 0, 0}
	CO      = tm.ScanCode{79, 0, 0, 0, 0, 0}
	CP      = tm.ScanCode{80, 0, 0, 0, 0, 0}
	CQ      = tm.ScanCode{81, 0, 0, 0, 0, 0}
	CR      = tm.ScanCode{82, 0, 0, 0, 0, 0}
	CS      = tm.ScanCode{83, 0, 0, 0, 0, 0}
	CT      = tm.ScanCode{84, 0, 0, 0, 0, 0}
	CU      = tm.ScanCode{85, 0, 0, 0, 0, 0}
	CV      = tm.ScanCode{86, 0, 0, 0, 0, 0}
	CW      = tm.ScanCode{87, 0, 0, 0, 0, 0}
	CX      = tm.ScanCode{88, 0, 0, 0, 0, 0}
	CY      = tm.ScanCode{89, 0, 0, 0, 0, 0}
	CZ      = tm.ScanCode{90, 0, 0, 0, 0, 0}

	Ca      = tm.ScanCode{97, 0, 0, 0, 0, 0}
	Cb      = tm.ScanCode{98, 0, 0, 0, 0, 0}
	Cc      = tm.ScanCode{99, 0, 0, 0, 0, 0}
	Cd      = tm.ScanCode{100, 0, 0, 0, 0, 0}
	Ce      = tm.ScanCode{101, 0, 0, 0, 0, 0}
	Cf      = tm.ScanCode{102, 0, 0, 0, 0, 0}
	Cg      = tm.ScanCode{103, 0, 0, 0, 0, 0}
	Ch      = tm.ScanCode{104, 0, 0, 0, 0, 0}
	Ci      = tm.ScanCode{105, 0, 0, 0, 0, 0}
	Cj      = tm.ScanCode{106, 0, 0, 0, 0, 0}
	Ck      = tm.ScanCode{107, 0, 0, 0, 0, 0}
	Cl      = tm.ScanCode{108, 0, 0, 0, 0, 0}
	Cm      = tm.ScanCode{109, 0, 0, 0, 0, 0}
	Cn      = tm.ScanCode{110, 0, 0, 0, 0, 0}
	Co      = tm.ScanCode{111, 0, 0, 0, 0, 0}
	Cp      = tm.ScanCode{112, 0, 0, 0, 0, 0}
	Cq      = tm.ScanCode{113, 0, 0, 0, 0, 0}
	Cr      = tm.ScanCode{114, 0, 0, 0, 0, 0}
	Cs      = tm.ScanCode{115, 0, 0, 0, 0, 0}
	Ct      = tm.ScanCode{116, 0, 0, 0, 0, 0}
	Cu      = tm.ScanCode{117, 0, 0, 0, 0, 0}
	Cv      = tm.ScanCode{118, 0, 0, 0, 0, 0}
	Cw      = tm.ScanCode{119, 0, 0, 0, 0, 0}
	Cx      = tm.ScanCode{120, 0, 0, 0, 0, 0}
	Cy      = tm.ScanCode{121, 0, 0, 0, 0, 0}
	Cz      = tm.ScanCode{122, 0, 0, 0, 0, 0}
)
