package codes

import tm "github.com/jonvaldes/termo"

var (
	ESC     = tm.ScanCode{27}
	UP      = tm.ScanCode{27, 91, 65}
	DOWN    = tm.ScanCode{27, 91, 66}
	LEFT    = tm.ScanCode{27, 91, 68}
	RIGHT   = tm.ScanCode{27, 91, 67}
	BACKSP  = tm.ScanCode{127}
	TAB     = tm.ScanCode{9}
	ENTER   = tm.ScanCode{13}
	HOME    = tm.ScanCode{27, 79, 72}
	END     = tm.ScanCode{27, 79, 70}

	//Autogenerated
	CA      = tm.ScanCode{65}
	CB      = tm.ScanCode{66}
	CC      = tm.ScanCode{67}
	CD      = tm.ScanCode{68}
	CE      = tm.ScanCode{69}
	CF      = tm.ScanCode{70}
	CG      = tm.ScanCode{71}
	CH      = tm.ScanCode{72}
	CI      = tm.ScanCode{73}
	CJ      = tm.ScanCode{74}
	CK      = tm.ScanCode{75}
	CL      = tm.ScanCode{76}
	CM      = tm.ScanCode{77}
	CN      = tm.ScanCode{78}
	CO      = tm.ScanCode{79}
	CP      = tm.ScanCode{80}
	CQ      = tm.ScanCode{81}
	CR      = tm.ScanCode{82}
	CS      = tm.ScanCode{83}
	CT      = tm.ScanCode{84}
	CU      = tm.ScanCode{85}
	CV      = tm.ScanCode{86}
	CW      = tm.ScanCode{87}
	CX      = tm.ScanCode{88}
	CY      = tm.ScanCode{89}
	CZ      = tm.ScanCode{90}
	Ca      = tm.ScanCode{97}
	Cb      = tm.ScanCode{98}
	Cc      = tm.ScanCode{99}
	Cd      = tm.ScanCode{100}
	Ce      = tm.ScanCode{101}
	Cf      = tm.ScanCode{102}
	Cg      = tm.ScanCode{103}
	Ch      = tm.ScanCode{104}
	Ci      = tm.ScanCode{105}
	Cj      = tm.ScanCode{106}
	Ck      = tm.ScanCode{107}
	Cl      = tm.ScanCode{108}
	Cm      = tm.ScanCode{109}
	Cn      = tm.ScanCode{110}
	Co      = tm.ScanCode{111}
	Cp      = tm.ScanCode{112}
	Cq      = tm.ScanCode{113}
	Cr      = tm.ScanCode{114}
	Cs      = tm.ScanCode{115}
	Ct      = tm.ScanCode{116}
	Cu      = tm.ScanCode{117}
	Cv      = tm.ScanCode{118}
	Cw      = tm.ScanCode{119}
	Cx      = tm.ScanCode{120}
	Cy      = tm.ScanCode{121}
	Cz      = tm.ScanCode{122}
)
